name: covector status
on: [pull_request]

jobs:
  covector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: covector status
        # note we are using the release branch temporarily awaiting a publish of these versions: https://github.com/jbolda/covector/pull/317
        #  those changes include updates to support commenting from forks
        uses: jbolda/covector/packages/action@release
        with:
          command: "status"
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: true
